server:
    port: 9090

logging:
    path: logs/

db:
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true

agent:
    sms:
      msg: 【VIPKID】您的验证码是%s。如非本人操作，请忽略本短信


spring:
    datasource:
      maximum-pool-size: 10
      driver-class-name: com.mysql.jdbc.Driver
      auto-commit: true
      connection-test-query: SELECT 1
      connectionTimeout: 20000
      maxLifetime: 180000
    mvc:
      favicon:
        enabled: false
    output:
      ansi:
        enabled: always
    application:
      name: agent-service
    zipkin:
      enabled: false

mapper:
    mappers:
        - com.vipkid.agent.utils.MyMapper
    not-empty: false
    identity: MYSQL

---
spring:
    profiles: production
    zipkin:
      enabled: true
endpoints:
  enabled: true
  autoconfig:
    enabled: true
  configprops:
    enabled: true
  dump:
    enabled: true
  health:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true
  shutdown:
    enabled: true
  restart:
    enabled: true
  env:
    enabled: true
  mappings:
    enabled: true
  beans:
    enabled: true
server:
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      prefix: localhost_access_log
      suffix: .log
      pattern: "%A|%h|%m|%t|%D|&quot;%r&quot;|&quot;%{Referer}i&quot;|&quot;%{User-Agent}i&quot;|%s|%S|%b|%{X-Request-ID}i|%{begin:msec}t|%{end:msec}t"
      rename-on-rotate: true

